sudo: required

language: java

services:
  - docker

script:
  - docker build -t upload-microservice .
after_success:
  - docker tag upload-microservice "$DOCKER_HUB_USERNAME"/upload-microservice:latest
  - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
  - docker push "$DOCKER_HUB_USERNAME"/upload-microservice:latest